### ISSUE TITLE
More accurate descriptions to links

### ISSUE THREAD

**Issue by woop** [woop/awesome-quantified-self#3]
The descriptions to many of the links to the products and services are quite generic. It would be quite useful if some of them could be rewritten by people that have actually used the products.

This would allow visitors to get a clearer picture of what differentiates the products and services.

**Comment by markwk** [comment]
I wondered about that too. I have longer descriptions but felt you limited this due to the style guidelines. Any ideas on a structure we might follow? First line probably should remain generic (?) but second line could be about best usage and what data it provides. 

I'm keen to focus on tools that make data easily reusable / exportable, etc.

**Comment by woop** [comment]
I think having one sentence descriptions would look better, but I also want important information of each link to be available. I guess the question becomes: what is relevant?

As an interim solution I think we should just stick to one line descriptions, and if it becomes too restrictive then we can revisit this. We can still flesh out the descriptions however. Most of the existing ones come directly from the respective product's website, which isn't ideal.
